version: '3'
services:
  app:
    build: .
    command: npm start
    volumes:
      - .:/usr/app
      - ./node_modules:/usr/app/node_modules
    ports:
      - "8080:8080"
    external_links:
      - mysql
    networks:
      - default

networks:
    default:
        external:
            name: laravellumendocker_default
